DB_CONFIG = {"user":"admin","password":"admin","database":"database","host":"localhost"}

POOL_MIN_SIZE = 5
POOL_MAX_SIZE = 12
POOL_MAX_QUERIES = 10000
POOL_MAX_INACTIVE_TIME = 300
CONNECTION_TIMEOUT = 3
QUERY_TIMEOUT = 15
MAX_PARTITION_RETRIES = 3
PARTITION_RETRY_DELAY = 0.1
HEALTH_CHECK_INTERVAL = 15
MAX_CONNECTION_FAILURES = 3
CIRCUIT_BREAKER_TIMEOUT = 30
CONNECTION_QUEUE_TIMEOUT = 3